### PR TITLE
create Github Workflow to automatic build/push docker image of anayway-repoters

### PR DESCRIPTION
**Pull request by mickeyrouash**
Add automatic build and push docker image of anyway-reports
Update and add an entry to k8s/values.auto-updated.yaml

### CODE REVIEW

**Comment by mickeyrouash** [comment]
@OriHoch @atalyaalon 
I tested it  on my local repo but some actions I can't do on my local repo( git commit on upstream)
Please add to  hasadna/anyway-reports repo secrets:
HASADNA_K8S_DEPLOY_KEY
DOCKER_PASSWORD
DOCKER_USERNAME

**Comment by OriHoch** [comment]
@mickeyrouash I added HASADNA_K8S_DEPLOY_KEY
regarding the docker secrets - I don't have them, so either send them to me privately if you have them or @atalyaalon could add them

**Comment by mickeyrouash** [comment]
@OriHoch @atalyaalon  I am using my docker hub user and password to push to anywayteam .
dose anywayteam have user and password ?

**Comment by OriHoch** [comment]
for automation you shouldn't use your personal username as this will allow to push to any repository you have access to

there should be an automation user, and if there isn't it's easy to create one

**Comment by mickeyrouash** [comment]
@OriHoch @atalyaalon I can create it but which email it will belong? I think you or Atalya should be the owner of this account

**Comment by OriHoch** [comment]
according to docker hub, there is a docker hub user `anywayci` which is used there, you should try to get the password for that user from @atalyaalon or whomever set that up

**Pull request merged**
